services:
  saveweb_archivesinavideo:
    image: git.saveweb.org/saveweb/sinavideo:latest
    restart: unless-stopped
    stop_grace_period: 2m
    environment:
      HQ_MACHINE_TOKEN: "hq_xxxxx"
#     volumes:
#       - warcs:/app/warcs
#       - temp:/app/temp

# volumes:
#   warcs:
#   temp:
